### ISSUE TITLE
How i setup the database?

### ISSUE THREAD

**Issue by byte-0x74** [k2cn/Forum#1]

**Comment by k2cn** [comment]
You need to rename the .env.example to .env, and then write this command in the terminal to generate an APPKEy. 

`php artisan key:generate`

After that you can either make a sqlite database or a mysql database, by editing the .env file

Sqlite
```
DB_CONNECTION=sqlite
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=/path/to/db/data.db
DB_USERNAME=root
DB_PASSWORD=
```

Mysql
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=DBNAME
DB_USERNAME=DBUSERNAME
DB_PASSWORD=DBPASSWORD
```

Then finally you can run the command 

`php artisan migrate:fresh --seed`

**Comment by byte-0x74** [comment]
Oh okay thanks.
